name: Build-Debug

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os == 'deb' && 'ubuntu-latest' || matrix.os == 'dmg' && 'macos-latest' || matrix.os == 'deb-arm' && 'ubuntu-24.04-arm' || 'windows-latest' }}
    strategy:
      matrix:
        os: [ deb-arm ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build packages
        run: |
          ./gradlew packageDistributionForCurrentOS -Preckon.scope=patch -Preckon.stage=final --info
