name: Release

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      scope:
        required: true
        type: string
    secrets:
        token:
            required: true

jobs:
  build:
    runs-on: ${{ matrix.os == 'deb' && 'ubuntu-latest' || matrix.os == 'dmg' && 'macos-latest' || 'windows-latest' }}
    strategy:
      matrix:
        os: [deb, dmg, msi]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Exit if not on main branch
        if: endsWith(github.ref, 'main') == false
        run: exit -1

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build packages
        run: ./gradlew -Preckon.scope=${{ inputs.scope }} -Preckon.stage=final package${{ matrix.os == 'deb' && 'Deb' || matrix.os == 'dmg' && 'Dmg' || 'Msi' }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.os }}
          path: ${{ matrix.os == 'deb' && 'composeApp/build/compose/binaries/main/deb' || matrix.os == 'dmg' && 'composeApp/build/compose/binaries/main/dmg' || 'composeApp/build/compose/binaries/main/msi' }}/*

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist

      - uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ inputs.tag }}"
          generate_release_notes: true
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
